version: 2
jobs:
  export-upload-resume:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.9
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Missing NPM Packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Export PDFs
          command: npm run export; cd pdfs; cp creative.pdf resume_beer.pdf;
      - run:
          name: Upload PDF
          command: aws s3 cp resume_beer.pdf s3://itsbeer --acl public-read;
workflows:
  version: 2
  export-upload-workflow:
    jobs:
      - approve-export-upload-resume:
          type: approval
      - export-upload-resume:
          requires:
            - approve-export-upload-resume
