version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  export-upload-resume:
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.9-browsers
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Missing NPM Packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Export PDFs
          command: npm run export; cd pdf; cp creative.pdf resume_beer.pdf;
      - aws-s3/copy:
          from: pdf/resume_beer.pdf
          to: "s3://itsbeer"
          arguments: |
            --acl public-read
workflows:
  version: 2
  export-upload-workflow:
    jobs:
      - approve-export-upload-resume:
          type: approval
      - export-upload-resume:
          requires:
            - approve-export-upload-resume
